/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['form[_ngcontent-%COMP%]{\n    padding-top: 10px;\n    padding-bottom: 10px;\n}\nbutton[_ngcontent-%COMP%]{\n    position:relative;\n    left: 42%;\n}\nfieldset.scheduler-border[_ngcontent-%COMP%] {\n    border: 2px groove #ddd !important;\n    padding: 0 1.4em 1.4em 1.4em !important;\n    margin: 0 0 1.5em 0 !important;\n\n\n    -webkit-box-shadow:  0px 0px 0px 0px #000;\n            box-shadow:  0px 0px 0px 0px #000;\n\n}\n\nlegend.scheduler-border[_ngcontent-%COMP%] {\n    font-size: 1.7em !important;\n    color: #ddd;\n    font-weight: bold !important;\n    text-align: left !important;\n    padding-left: 20px;\n    padding-top: 4px;\n    padding-bottom: 4px;\n    background-color: rgb(11, 59, 95);\n}\n.form-control[_ngcontent-%COMP%]{\n    border-width: 2px;\n}\n\n.headd[_ngcontent-%COMP%]{\n    font-family: \'Open Sans\', sans-serif;\n  }\n\na[_ngcontent-%COMP%]{\n    float:right;\n    margin-left:60%;\n    background:#6666ff;\n    color:white;\n    font-weight:bolder;\n    padding: 11px 22px 11px 22px;\n  }\n  \nh2[_ngcontent-%COMP%]{\n    float:left;\n    margin-left:05%;\n  }\n  \ndiv#mainhd[_ngcontent-%COMP%]{\n    background-color:white;\n    width:100%;\n  }\n\n#wrapper[_ngcontent-%COMP%]{\n    display:flex;\n    align-items:center;\n    height:8em;\n    margin-bottom:30px;\n  }\nlabel[_ngcontent-%COMP%]{\n    font-weight: 900;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL21udC9ENkIwQzlGREIwQzlFM0Q5L1BhdGllbnQvYXNzZXRzL2FwcC9wYXRmb3JtL3BhdGZvcm0uY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9tbnQvRDZCMEM5RkRCMEM5RTNEOS9QYXRpZW50L2Fzc2V0cy9hcHAvcGF0Zm9ybS9wYXRmb3JtLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
